[package]
name = "protogen"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.1.11"
x86 = "0.52.0"
x86_64 = "0.14.10"
spin = "0.9.8"
paste = "1"
aligned-array = "1"
kernel-macros = {path = "../kernel-macros"}
[build-dependencies]
cc = "1.0"